- name: Ansible copy directory to the remote server
  copy:
    src: ./project_files/task3
    dest: /opt/
    mode: '755'
- name: Creates a cron file under /etc/cron.d
  cron:
    job: /opt/task3/collect_data.sh
    hour: '1'
- name: Change the working directory to somedir/ before executing the command
  shell: docker-compose up  -d && sleep 30 && /usr/bin/bash /opt/task3/collect_data.sh
  args:
    chdir: /opt/task3
