version: '3'
services:
  app:
    build: .
    command: /usr/bin/python3 /opt/main.py
    privileged: true
    restart: on-failure
    links:
      - db
    depends_on:
      - db
    ports:
      - '5000:5000'
    container_name: my-app-container
  db:
    image: mysql
    command: '--default-authentication-plugin=mysql_native_password'
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 123
    container_name: my-sql-container
    volumes:
      - './db:/docker-entrypoint-initdb.d/:ro'
